In [8]:
import numpy as np

# numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

# Parameters

- start: Start of interval. The interval includes this value. The default start value is 0.

- stop: End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

- step: Spacing between values. The default step size is 1. If step is specified as a position argument, start must also be given.

# Returns

Array of evenly spaced values.

In [9]:
Z = 10 + np.arange(90) # Create a vector with values ranging from 10 to 99
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [10]:
Z = np.arange(9).reshape(3,3) # Create a 3x3 matrix with values ranging from 0 to 8
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
